### PR TITLE
Remove embedded body on click handler

### PR DESCRIPTION
**Pull request by AD7six**
When editing your projects this causes the page to jump to the top each time you click, forcing you to scroll _a lot_ if you have more than one page of projects to action.

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
@inkel added this line in 46f4abe3, I'm not sure what it does. Could you enlighten us, Leandro? :)

**Comment by inkel** [comment]
I clear made a mistake, it should have been `onload`.

This is a hack for iOS 4 devices, to hide the browser bar when first loading a long page. What @AD7six says is correctly, been `onclick` is annoying. It is not required in order to make the site fully working, so I think the change it's ok :)

**Comment by edtsech** [comment]
I vote for merge. It's really annoying.

**Comment by doriath** [comment]
I changed the `onclick` to the `onload` in 7dbac088c941b34a273126a13b27ac0baa30430b. I am closing this issue. Thank you @AD7six for finding and fixing this bug.

**Comment by doriath** [comment]
Hey,

I didn't merge the pull request because I wanted to change the _onclick_ to
_onload_ (instead of removing that). I should have mention the issue and
pull request of @AD7Six in commit message. Sorry for not doing that.

Thanks,
Tomasz

**Pull request closed without merging**
